version: '3'
services:
 server:
  build: ./
  container_name: server
  restart: always
  ports:
   - 3001:3001
  volumes:
   - ./:/app
  command: npm run start:dev
  depends_on:
   - mongo
 mongo:
  image: mongo
  container_name: mongo
  restart: always
  environment:
   - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
  ports:
   - 27019:27017
  volumes:
   - ./mongo-data:/data/db
