version: '3'
services:
  it-city:
    build: ./
    container_name: it-city
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /node_modules
      - /server
      - /.next
    depends_on:
      - server
  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - 3001:3001
