services:
  front:
    build: front
    container_name: front
    restart: always
    ports:
      - 8080:3000
    expose:
      - 8080
    develop:
      watch:
        - action: rebuild
          path: ./front
          target: /app
          ignore:
            - node_modules/
              templates/
              .eslintrc.json
              .gitignore
              .prettierrc
              generate-react-cli.json
              README.md
              Прайс-лист_03.02.24 (1).xlsx
              услуги.xlsx
    depends_on:
      - serverit
  serverit:
    build: back
    container_name: server
    restart: always
    expose:
      - 3001
    ports:
      - 3001:3001
    develop:
      watch:
        - action: rebuild
          path: ./back
          target: /app
          ignore:
            - node_modules/
              templates/
              .eslintrc.json
              .gitignore
              .prettierrc
              README.md
              Dockerfile
              .dockerignore
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27019:27017
    volumes:
      - ./mongo-data:/data/db
